[local_phases]
unit = "rspec"
lint = "rubocop"
syntax = "foodcritic ."
provision = "echo Skipping..."
deploy = "echo Skipping..."
smoke = "echo 'Skipping - Use Test Kitchen directly...'"
functional = "echo 'Skipping - Use Test Kitchen directly...'"
cleanup = "echo Skipping..."
